# Generated by Django 4.2.2 on 2024-05-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
