# Generated by Django 4.2.2 on 2024-05-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_timetable_timeslot_timetable_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.instructor'),
        ),
    ]
