# Generated by Django 4.2.2 on 2024-05-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_timetable_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='instructor',
        ),
    ]
